// AUTO-GENERATED by scripts/gen-countries.mjs from the `world-countries` dataset.
// Do not edit by hand — run `npm run gen:countries` to regenerate.

export type Continent =
  | 'Africa'
  | 'Asia'
  | 'Europe'
  | 'North America'
  | 'South America'
  | 'Oceania'
  | 'Antarctica'
  | 'Other'

export type Country = {
  a3: string // ISO 3166-1 alpha-3 — the key for persisted state
  numericId: string // ISO 3166-1 numeric, leading zeros stripped (matches world-atlas feature ids)
  name: string
  continent: Continent
  subregion: string
  flag: string // emoji
  counts: boolean // UN member — counts toward the "% of the world" denominator
}

export const COUNTRIES: Country[] = [
  {
    "a3": "AFG",
    "numericId": "4",
    "name": "Afghanistan",
    "continent": "Asia",
    "subregion": "Southern Asia",
    "flag": "🇦🇫",
    "counts": true
  },
  {
    "a3": "ALA",
    "numericId": "248",
    "name": "Åland Islands",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇦🇽",
    "counts": false
  },
  {
    "a3": "ALB",
    "numericId": "8",
    "name": "Albania",
    "continent": "Europe",
    "subregion": "Southeast Europe",
    "flag": "🇦🇱",
    "counts": true
  },
  {
    "a3": "DZA",
    "numericId": "12",
    "name": "Algeria",
    "continent": "Africa",
    "subregion": "Northern Africa",
    "flag": "🇩🇿",
    "counts": true
  },
  {
    "a3": "ASM",
    "numericId": "16",
    "name": "American Samoa",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇦🇸",
    "counts": false
  },
  {
    "a3": "AND",
    "numericId": "20",
    "name": "Andorra",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇦🇩",
    "counts": true
  },
  {
    "a3": "AGO",
    "numericId": "24",
    "name": "Angola",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇦🇴",
    "counts": true
  },
  {
    "a3": "AIA",
    "numericId": "660",
    "name": "Anguilla",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇦🇮",
    "counts": false
  },
  {
    "a3": "ATA",
    "numericId": "10",
    "name": "Antarctica",
    "continent": "Antarctica",
    "subregion": "Other",
    "flag": "🇦🇶",
    "counts": false
  },
  {
    "a3": "ATG",
    "numericId": "28",
    "name": "Antigua and Barbuda",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇦🇬",
    "counts": true
  },
  {
    "a3": "ARG",
    "numericId": "32",
    "name": "Argentina",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇦🇷",
    "counts": true
  },
  {
    "a3": "ARM",
    "numericId": "51",
    "name": "Armenia",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇦🇲",
    "counts": true
  },
  {
    "a3": "ABW",
    "numericId": "533",
    "name": "Aruba",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇦🇼",
    "counts": false
  },
  {
    "a3": "AUS",
    "numericId": "36",
    "name": "Australia",
    "continent": "Oceania",
    "subregion": "Australia and New Zealand",
    "flag": "🇦🇺",
    "counts": true
  },
  {
    "a3": "AUT",
    "numericId": "40",
    "name": "Austria",
    "continent": "Europe",
    "subregion": "Central Europe",
    "flag": "🇦🇹",
    "counts": true
  },
  {
    "a3": "AZE",
    "numericId": "31",
    "name": "Azerbaijan",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇦🇿",
    "counts": true
  },
  {
    "a3": "BHS",
    "numericId": "44",
    "name": "Bahamas",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇧🇸",
    "counts": true
  },
  {
    "a3": "BHR",
    "numericId": "48",
    "name": "Bahrain",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇧🇭",
    "counts": true
  },
  {
    "a3": "BGD",
    "numericId": "50",
    "name": "Bangladesh",
    "continent": "Asia",
    "subregion": "Southern Asia",
    "flag": "🇧🇩",
    "counts": true
  },
  {
    "a3": "BRB",
    "numericId": "52",
    "name": "Barbados",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇧🇧",
    "counts": true
  },
  {
    "a3": "BLR",
    "numericId": "112",
    "name": "Belarus",
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "flag": "🇧🇾",
    "counts": true
  },
  {
    "a3": "BEL",
    "numericId": "56",
    "name": "Belgium",
    "continent": "Europe",
    "subregion": "Western Europe",
    "flag": "🇧🇪",
    "counts": true
  },
  {
    "a3": "BLZ",
    "numericId": "84",
    "name": "Belize",
    "continent": "North America",
    "subregion": "Central America",
    "flag": "🇧🇿",
    "counts": true
  },
  {
    "a3": "BEN",
    "numericId": "204",
    "name": "Benin",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇧🇯",
    "counts": true
  },
  {
    "a3": "BMU",
    "numericId": "60",
    "name": "Bermuda",
    "continent": "North America",
    "subregion": "North America",
    "flag": "🇧🇲",
    "counts": false
  },
  {
    "a3": "BTN",
    "numericId": "64",
    "name": "Bhutan",
    "continent": "Asia",
    "subregion": "Southern Asia",
    "flag": "🇧🇹",
    "counts": true
  },
  {
    "a3": "BOL",
    "numericId": "68",
    "name": "Bolivia",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇧🇴",
    "counts": true
  },
  {
    "a3": "BIH",
    "numericId": "70",
    "name": "Bosnia and Herzegovina",
    "continent": "Europe",
    "subregion": "Southeast Europe",
    "flag": "🇧🇦",
    "counts": true
  },
  {
    "a3": "BWA",
    "numericId": "72",
    "name": "Botswana",
    "continent": "Africa",
    "subregion": "Southern Africa",
    "flag": "🇧🇼",
    "counts": true
  },
  {
    "a3": "BVT",
    "numericId": "74",
    "name": "Bouvet Island",
    "continent": "Antarctica",
    "subregion": "Other",
    "flag": "🇧🇻",
    "counts": false
  },
  {
    "a3": "BRA",
    "numericId": "76",
    "name": "Brazil",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇧🇷",
    "counts": true
  },
  {
    "a3": "IOT",
    "numericId": "86",
    "name": "British Indian Ocean Territory",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇮🇴",
    "counts": false
  },
  {
    "a3": "VGB",
    "numericId": "92",
    "name": "British Virgin Islands",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇻🇬",
    "counts": false
  },
  {
    "a3": "BRN",
    "numericId": "96",
    "name": "Brunei",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇧🇳",
    "counts": true
  },
  {
    "a3": "BGR",
    "numericId": "100",
    "name": "Bulgaria",
    "continent": "Europe",
    "subregion": "Southeast Europe",
    "flag": "🇧🇬",
    "counts": true
  },
  {
    "a3": "BFA",
    "numericId": "854",
    "name": "Burkina Faso",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇧🇫",
    "counts": true
  },
  {
    "a3": "BDI",
    "numericId": "108",
    "name": "Burundi",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇧🇮",
    "counts": true
  },
  {
    "a3": "KHM",
    "numericId": "116",
    "name": "Cambodia",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇰🇭",
    "counts": true
  },
  {
    "a3": "CMR",
    "numericId": "120",
    "name": "Cameroon",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇨🇲",
    "counts": true
  },
  {
    "a3": "CAN",
    "numericId": "124",
    "name": "Canada",
    "continent": "North America",
    "subregion": "North America",
    "flag": "🇨🇦",
    "counts": true
  },
  {
    "a3": "CPV",
    "numericId": "132",
    "name": "Cape Verde",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇨🇻",
    "counts": true
  },
  {
    "a3": "BES",
    "numericId": "535",
    "name": "Caribbean Netherlands",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "",
    "counts": false
  },
  {
    "a3": "CYM",
    "numericId": "136",
    "name": "Cayman Islands",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇰🇾",
    "counts": false
  },
  {
    "a3": "CAF",
    "numericId": "140",
    "name": "Central African Republic",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇨🇫",
    "counts": true
  },
  {
    "a3": "TCD",
    "numericId": "148",
    "name": "Chad",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇹🇩",
    "counts": true
  },
  {
    "a3": "CHL",
    "numericId": "152",
    "name": "Chile",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇨🇱",
    "counts": true
  },
  {
    "a3": "CHN",
    "numericId": "156",
    "name": "China",
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "flag": "🇨🇳",
    "counts": true
  },
  {
    "a3": "CXR",
    "numericId": "162",
    "name": "Christmas Island",
    "continent": "Oceania",
    "subregion": "Australia and New Zealand",
    "flag": "🇨🇽",
    "counts": false
  },
  {
    "a3": "CCK",
    "numericId": "166",
    "name": "Cocos (Keeling) Islands",
    "continent": "Oceania",
    "subregion": "Australia and New Zealand",
    "flag": "🇨🇨",
    "counts": false
  },
  {
    "a3": "COL",
    "numericId": "170",
    "name": "Colombia",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇨🇴",
    "counts": true
  },
  {
    "a3": "COM",
    "numericId": "174",
    "name": "Comoros",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇰🇲",
    "counts": true
  },
  {
    "a3": "COK",
    "numericId": "184",
    "name": "Cook Islands",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇨🇰",
    "counts": false
  },
  {
    "a3": "CRI",
    "numericId": "188",
    "name": "Costa Rica",
    "continent": "North America",
    "subregion": "Central America",
    "flag": "🇨🇷",
    "counts": true
  },
  {
    "a3": "HRV",
    "numericId": "191",
    "name": "Croatia",
    "continent": "Europe",
    "subregion": "Southeast Europe",
    "flag": "🇭🇷",
    "counts": true
  },
  {
    "a3": "CUB",
    "numericId": "192",
    "name": "Cuba",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇨🇺",
    "counts": true
  },
  {
    "a3": "CUW",
    "numericId": "531",
    "name": "Curaçao",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇨🇼",
    "counts": false
  },
  {
    "a3": "CYP",
    "numericId": "196",
    "name": "Cyprus",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇨🇾",
    "counts": true
  },
  {
    "a3": "CZE",
    "numericId": "203",
    "name": "Czechia",
    "continent": "Europe",
    "subregion": "Central Europe",
    "flag": "🇨🇿",
    "counts": true
  },
  {
    "a3": "DNK",
    "numericId": "208",
    "name": "Denmark",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇩🇰",
    "counts": true
  },
  {
    "a3": "DJI",
    "numericId": "262",
    "name": "Djibouti",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇩🇯",
    "counts": true
  },
  {
    "a3": "DMA",
    "numericId": "212",
    "name": "Dominica",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇩🇲",
    "counts": true
  },
  {
    "a3": "DOM",
    "numericId": "214",
    "name": "Dominican Republic",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇩🇴",
    "counts": true
  },
  {
    "a3": "COD",
    "numericId": "180",
    "name": "DR Congo",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇨🇩",
    "counts": true
  },
  {
    "a3": "ECU",
    "numericId": "218",
    "name": "Ecuador",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇪🇨",
    "counts": true
  },
  {
    "a3": "EGY",
    "numericId": "818",
    "name": "Egypt",
    "continent": "Africa",
    "subregion": "Northern Africa",
    "flag": "🇪🇬",
    "counts": true
  },
  {
    "a3": "SLV",
    "numericId": "222",
    "name": "El Salvador",
    "continent": "North America",
    "subregion": "Central America",
    "flag": "🇸🇻",
    "counts": true
  },
  {
    "a3": "GNQ",
    "numericId": "226",
    "name": "Equatorial Guinea",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇬🇶",
    "counts": true
  },
  {
    "a3": "ERI",
    "numericId": "232",
    "name": "Eritrea",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇪🇷",
    "counts": true
  },
  {
    "a3": "EST",
    "numericId": "233",
    "name": "Estonia",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇪🇪",
    "counts": true
  },
  {
    "a3": "SWZ",
    "numericId": "748",
    "name": "Eswatini",
    "continent": "Africa",
    "subregion": "Southern Africa",
    "flag": "🇸🇿",
    "counts": true
  },
  {
    "a3": "ETH",
    "numericId": "231",
    "name": "Ethiopia",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇪🇹",
    "counts": true
  },
  {
    "a3": "FLK",
    "numericId": "238",
    "name": "Falkland Islands",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇫🇰",
    "counts": false
  },
  {
    "a3": "FRO",
    "numericId": "234",
    "name": "Faroe Islands",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇫🇴",
    "counts": false
  },
  {
    "a3": "FJI",
    "numericId": "242",
    "name": "Fiji",
    "continent": "Oceania",
    "subregion": "Melanesia",
    "flag": "🇫🇯",
    "counts": true
  },
  {
    "a3": "FIN",
    "numericId": "246",
    "name": "Finland",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇫🇮",
    "counts": true
  },
  {
    "a3": "FRA",
    "numericId": "250",
    "name": "France",
    "continent": "Europe",
    "subregion": "Western Europe",
    "flag": "🇫🇷",
    "counts": true
  },
  {
    "a3": "GUF",
    "numericId": "254",
    "name": "French Guiana",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇬🇫",
    "counts": false
  },
  {
    "a3": "PYF",
    "numericId": "258",
    "name": "French Polynesia",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇵🇫",
    "counts": false
  },
  {
    "a3": "ATF",
    "numericId": "260",
    "name": "French Southern and Antarctic Lands",
    "continent": "Antarctica",
    "subregion": "Other",
    "flag": "🇹🇫",
    "counts": false
  },
  {
    "a3": "GAB",
    "numericId": "266",
    "name": "Gabon",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇬🇦",
    "counts": true
  },
  {
    "a3": "GMB",
    "numericId": "270",
    "name": "Gambia",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇬🇲",
    "counts": true
  },
  {
    "a3": "GEO",
    "numericId": "268",
    "name": "Georgia",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇬🇪",
    "counts": true
  },
  {
    "a3": "DEU",
    "numericId": "276",
    "name": "Germany",
    "continent": "Europe",
    "subregion": "Western Europe",
    "flag": "🇩🇪",
    "counts": true
  },
  {
    "a3": "GHA",
    "numericId": "288",
    "name": "Ghana",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇬🇭",
    "counts": true
  },
  {
    "a3": "GIB",
    "numericId": "292",
    "name": "Gibraltar",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇬🇮",
    "counts": false
  },
  {
    "a3": "GRC",
    "numericId": "300",
    "name": "Greece",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇬🇷",
    "counts": true
  },
  {
    "a3": "GRL",
    "numericId": "304",
    "name": "Greenland",
    "continent": "North America",
    "subregion": "North America",
    "flag": "🇬🇱",
    "counts": false
  },
  {
    "a3": "GRD",
    "numericId": "308",
    "name": "Grenada",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇬🇩",
    "counts": true
  },
  {
    "a3": "GLP",
    "numericId": "312",
    "name": "Guadeloupe",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇬🇵",
    "counts": false
  },
  {
    "a3": "GUM",
    "numericId": "316",
    "name": "Guam",
    "continent": "Oceania",
    "subregion": "Micronesia",
    "flag": "🇬🇺",
    "counts": false
  },
  {
    "a3": "GTM",
    "numericId": "320",
    "name": "Guatemala",
    "continent": "North America",
    "subregion": "Central America",
    "flag": "🇬🇹",
    "counts": true
  },
  {
    "a3": "GGY",
    "numericId": "831",
    "name": "Guernsey",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇬🇬",
    "counts": false
  },
  {
    "a3": "GIN",
    "numericId": "324",
    "name": "Guinea",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇬🇳",
    "counts": true
  },
  {
    "a3": "GNB",
    "numericId": "624",
    "name": "Guinea-Bissau",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇬🇼",
    "counts": true
  },
  {
    "a3": "GUY",
    "numericId": "328",
    "name": "Guyana",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇬🇾",
    "counts": true
  },
  {
    "a3": "HTI",
    "numericId": "332",
    "name": "Haiti",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇭🇹",
    "counts": true
  },
  {
    "a3": "HMD",
    "numericId": "334",
    "name": "Heard Island and McDonald Islands",
    "continent": "Antarctica",
    "subregion": "Other",
    "flag": "🇭🇲",
    "counts": false
  },
  {
    "a3": "HND",
    "numericId": "340",
    "name": "Honduras",
    "continent": "North America",
    "subregion": "Central America",
    "flag": "🇭🇳",
    "counts": true
  },
  {
    "a3": "HKG",
    "numericId": "344",
    "name": "Hong Kong",
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "flag": "🇭🇰",
    "counts": false
  },
  {
    "a3": "HUN",
    "numericId": "348",
    "name": "Hungary",
    "continent": "Europe",
    "subregion": "Central Europe",
    "flag": "🇭🇺",
    "counts": true
  },
  {
    "a3": "ISL",
    "numericId": "352",
    "name": "Iceland",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇮🇸",
    "counts": true
  },
  {
    "a3": "IND",
    "numericId": "356",
    "name": "India",
    "continent": "Asia",
    "subregion": "Southern Asia",
    "flag": "🇮🇳",
    "counts": true
  },
  {
    "a3": "IDN",
    "numericId": "360",
    "name": "Indonesia",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇮🇩",
    "counts": true
  },
  {
    "a3": "IRN",
    "numericId": "364",
    "name": "Iran",
    "continent": "Asia",
    "subregion": "Southern Asia",
    "flag": "🇮🇷",
    "counts": true
  },
  {
    "a3": "IRQ",
    "numericId": "368",
    "name": "Iraq",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇮🇶",
    "counts": true
  },
  {
    "a3": "IRL",
    "numericId": "372",
    "name": "Ireland",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇮🇪",
    "counts": true
  },
  {
    "a3": "IMN",
    "numericId": "833",
    "name": "Isle of Man",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇮🇲",
    "counts": false
  },
  {
    "a3": "ISR",
    "numericId": "376",
    "name": "Israel",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇮🇱",
    "counts": true
  },
  {
    "a3": "ITA",
    "numericId": "380",
    "name": "Italy",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇮🇹",
    "counts": true
  },
  {
    "a3": "CIV",
    "numericId": "384",
    "name": "Ivory Coast",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇨🇮",
    "counts": true
  },
  {
    "a3": "JAM",
    "numericId": "388",
    "name": "Jamaica",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇯🇲",
    "counts": true
  },
  {
    "a3": "JPN",
    "numericId": "392",
    "name": "Japan",
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "flag": "🇯🇵",
    "counts": true
  },
  {
    "a3": "JEY",
    "numericId": "832",
    "name": "Jersey",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇯🇪",
    "counts": false
  },
  {
    "a3": "JOR",
    "numericId": "400",
    "name": "Jordan",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇯🇴",
    "counts": true
  },
  {
    "a3": "KAZ",
    "numericId": "398",
    "name": "Kazakhstan",
    "continent": "Asia",
    "subregion": "Central Asia",
    "flag": "🇰🇿",
    "counts": true
  },
  {
    "a3": "KEN",
    "numericId": "404",
    "name": "Kenya",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇰🇪",
    "counts": true
  },
  {
    "a3": "KIR",
    "numericId": "296",
    "name": "Kiribati",
    "continent": "Oceania",
    "subregion": "Micronesia",
    "flag": "🇰🇮",
    "counts": true
  },
  {
    "a3": "UNK",
    "numericId": "",
    "name": "Kosovo",
    "continent": "Europe",
    "subregion": "Southeast Europe",
    "flag": "🇽🇰",
    "counts": false
  },
  {
    "a3": "KWT",
    "numericId": "414",
    "name": "Kuwait",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇰🇼",
    "counts": true
  },
  {
    "a3": "KGZ",
    "numericId": "417",
    "name": "Kyrgyzstan",
    "continent": "Asia",
    "subregion": "Central Asia",
    "flag": "🇰🇬",
    "counts": true
  },
  {
    "a3": "LAO",
    "numericId": "418",
    "name": "Laos",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇱🇦",
    "counts": true
  },
  {
    "a3": "LVA",
    "numericId": "428",
    "name": "Latvia",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇱🇻",
    "counts": true
  },
  {
    "a3": "LBN",
    "numericId": "422",
    "name": "Lebanon",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇱🇧",
    "counts": true
  },
  {
    "a3": "LSO",
    "numericId": "426",
    "name": "Lesotho",
    "continent": "Africa",
    "subregion": "Southern Africa",
    "flag": "🇱🇸",
    "counts": true
  },
  {
    "a3": "LBR",
    "numericId": "430",
    "name": "Liberia",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇱🇷",
    "counts": true
  },
  {
    "a3": "LBY",
    "numericId": "434",
    "name": "Libya",
    "continent": "Africa",
    "subregion": "Northern Africa",
    "flag": "🇱🇾",
    "counts": true
  },
  {
    "a3": "LIE",
    "numericId": "438",
    "name": "Liechtenstein",
    "continent": "Europe",
    "subregion": "Western Europe",
    "flag": "🇱🇮",
    "counts": true
  },
  {
    "a3": "LTU",
    "numericId": "440",
    "name": "Lithuania",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇱🇹",
    "counts": true
  },
  {
    "a3": "LUX",
    "numericId": "442",
    "name": "Luxembourg",
    "continent": "Europe",
    "subregion": "Western Europe",
    "flag": "🇱🇺",
    "counts": true
  },
  {
    "a3": "MAC",
    "numericId": "446",
    "name": "Macau",
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "flag": "🇲🇴",
    "counts": false
  },
  {
    "a3": "MDG",
    "numericId": "450",
    "name": "Madagascar",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇲🇬",
    "counts": true
  },
  {
    "a3": "MWI",
    "numericId": "454",
    "name": "Malawi",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇲🇼",
    "counts": true
  },
  {
    "a3": "MYS",
    "numericId": "458",
    "name": "Malaysia",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇲🇾",
    "counts": true
  },
  {
    "a3": "MDV",
    "numericId": "462",
    "name": "Maldives",
    "continent": "Asia",
    "subregion": "Southern Asia",
    "flag": "🇲🇻",
    "counts": true
  },
  {
    "a3": "MLI",
    "numericId": "466",
    "name": "Mali",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇲🇱",
    "counts": true
  },
  {
    "a3": "MLT",
    "numericId": "470",
    "name": "Malta",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇲🇹",
    "counts": true
  },
  {
    "a3": "MHL",
    "numericId": "584",
    "name": "Marshall Islands",
    "continent": "Oceania",
    "subregion": "Micronesia",
    "flag": "🇲🇭",
    "counts": true
  },
  {
    "a3": "MTQ",
    "numericId": "474",
    "name": "Martinique",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇲🇶",
    "counts": false
  },
  {
    "a3": "MRT",
    "numericId": "478",
    "name": "Mauritania",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇲🇷",
    "counts": true
  },
  {
    "a3": "MUS",
    "numericId": "480",
    "name": "Mauritius",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇲🇺",
    "counts": true
  },
  {
    "a3": "MYT",
    "numericId": "175",
    "name": "Mayotte",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇾🇹",
    "counts": false
  },
  {
    "a3": "MEX",
    "numericId": "484",
    "name": "Mexico",
    "continent": "North America",
    "subregion": "North America",
    "flag": "🇲🇽",
    "counts": true
  },
  {
    "a3": "FSM",
    "numericId": "583",
    "name": "Micronesia",
    "continent": "Oceania",
    "subregion": "Micronesia",
    "flag": "🇫🇲",
    "counts": true
  },
  {
    "a3": "MDA",
    "numericId": "498",
    "name": "Moldova",
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "flag": "🇲🇩",
    "counts": true
  },
  {
    "a3": "MCO",
    "numericId": "492",
    "name": "Monaco",
    "continent": "Europe",
    "subregion": "Western Europe",
    "flag": "🇲🇨",
    "counts": true
  },
  {
    "a3": "MNG",
    "numericId": "496",
    "name": "Mongolia",
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "flag": "🇲🇳",
    "counts": true
  },
  {
    "a3": "MNE",
    "numericId": "499",
    "name": "Montenegro",
    "continent": "Europe",
    "subregion": "Southeast Europe",
    "flag": "🇲🇪",
    "counts": true
  },
  {
    "a3": "MSR",
    "numericId": "500",
    "name": "Montserrat",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇲🇸",
    "counts": false
  },
  {
    "a3": "MAR",
    "numericId": "504",
    "name": "Morocco",
    "continent": "Africa",
    "subregion": "Northern Africa",
    "flag": "🇲🇦",
    "counts": true
  },
  {
    "a3": "MOZ",
    "numericId": "508",
    "name": "Mozambique",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇲🇿",
    "counts": true
  },
  {
    "a3": "MMR",
    "numericId": "104",
    "name": "Myanmar",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇲🇲",
    "counts": true
  },
  {
    "a3": "NAM",
    "numericId": "516",
    "name": "Namibia",
    "continent": "Africa",
    "subregion": "Southern Africa",
    "flag": "🇳🇦",
    "counts": true
  },
  {
    "a3": "NRU",
    "numericId": "520",
    "name": "Nauru",
    "continent": "Oceania",
    "subregion": "Micronesia",
    "flag": "🇳🇷",
    "counts": true
  },
  {
    "a3": "NPL",
    "numericId": "524",
    "name": "Nepal",
    "continent": "Asia",
    "subregion": "Southern Asia",
    "flag": "🇳🇵",
    "counts": true
  },
  {
    "a3": "NLD",
    "numericId": "528",
    "name": "Netherlands",
    "continent": "Europe",
    "subregion": "Western Europe",
    "flag": "🇳🇱",
    "counts": true
  },
  {
    "a3": "NCL",
    "numericId": "540",
    "name": "New Caledonia",
    "continent": "Oceania",
    "subregion": "Melanesia",
    "flag": "🇳🇨",
    "counts": false
  },
  {
    "a3": "NZL",
    "numericId": "554",
    "name": "New Zealand",
    "continent": "Oceania",
    "subregion": "Australia and New Zealand",
    "flag": "🇳🇿",
    "counts": true
  },
  {
    "a3": "NIC",
    "numericId": "558",
    "name": "Nicaragua",
    "continent": "North America",
    "subregion": "Central America",
    "flag": "🇳🇮",
    "counts": true
  },
  {
    "a3": "NER",
    "numericId": "562",
    "name": "Niger",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇳🇪",
    "counts": true
  },
  {
    "a3": "NGA",
    "numericId": "566",
    "name": "Nigeria",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇳🇬",
    "counts": true
  },
  {
    "a3": "NIU",
    "numericId": "570",
    "name": "Niue",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇳🇺",
    "counts": false
  },
  {
    "a3": "NFK",
    "numericId": "574",
    "name": "Norfolk Island",
    "continent": "Oceania",
    "subregion": "Australia and New Zealand",
    "flag": "🇳🇫",
    "counts": false
  },
  {
    "a3": "PRK",
    "numericId": "408",
    "name": "North Korea",
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "flag": "🇰🇵",
    "counts": true
  },
  {
    "a3": "MKD",
    "numericId": "807",
    "name": "North Macedonia",
    "continent": "Europe",
    "subregion": "Southeast Europe",
    "flag": "🇲🇰",
    "counts": true
  },
  {
    "a3": "MNP",
    "numericId": "580",
    "name": "Northern Mariana Islands",
    "continent": "Oceania",
    "subregion": "Micronesia",
    "flag": "🇲🇵",
    "counts": false
  },
  {
    "a3": "NOR",
    "numericId": "578",
    "name": "Norway",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇳🇴",
    "counts": true
  },
  {
    "a3": "OMN",
    "numericId": "512",
    "name": "Oman",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇴🇲",
    "counts": true
  },
  {
    "a3": "PAK",
    "numericId": "586",
    "name": "Pakistan",
    "continent": "Asia",
    "subregion": "Southern Asia",
    "flag": "🇵🇰",
    "counts": true
  },
  {
    "a3": "PLW",
    "numericId": "585",
    "name": "Palau",
    "continent": "Oceania",
    "subregion": "Micronesia",
    "flag": "🇵🇼",
    "counts": true
  },
  {
    "a3": "PSE",
    "numericId": "275",
    "name": "Palestine",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇵🇸",
    "counts": false
  },
  {
    "a3": "PAN",
    "numericId": "591",
    "name": "Panama",
    "continent": "North America",
    "subregion": "Central America",
    "flag": "🇵🇦",
    "counts": true
  },
  {
    "a3": "PNG",
    "numericId": "598",
    "name": "Papua New Guinea",
    "continent": "Oceania",
    "subregion": "Melanesia",
    "flag": "🇵🇬",
    "counts": true
  },
  {
    "a3": "PRY",
    "numericId": "600",
    "name": "Paraguay",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇵🇾",
    "counts": true
  },
  {
    "a3": "PER",
    "numericId": "604",
    "name": "Peru",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇵🇪",
    "counts": true
  },
  {
    "a3": "PHL",
    "numericId": "608",
    "name": "Philippines",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇵🇭",
    "counts": true
  },
  {
    "a3": "PCN",
    "numericId": "612",
    "name": "Pitcairn Islands",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇵🇳",
    "counts": false
  },
  {
    "a3": "POL",
    "numericId": "616",
    "name": "Poland",
    "continent": "Europe",
    "subregion": "Central Europe",
    "flag": "🇵🇱",
    "counts": true
  },
  {
    "a3": "PRT",
    "numericId": "620",
    "name": "Portugal",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇵🇹",
    "counts": true
  },
  {
    "a3": "PRI",
    "numericId": "630",
    "name": "Puerto Rico",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇵🇷",
    "counts": false
  },
  {
    "a3": "QAT",
    "numericId": "634",
    "name": "Qatar",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇶🇦",
    "counts": true
  },
  {
    "a3": "COG",
    "numericId": "178",
    "name": "Republic of the Congo",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇨🇬",
    "counts": true
  },
  {
    "a3": "REU",
    "numericId": "638",
    "name": "Réunion",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇷🇪",
    "counts": false
  },
  {
    "a3": "ROU",
    "numericId": "642",
    "name": "Romania",
    "continent": "Europe",
    "subregion": "Southeast Europe",
    "flag": "🇷🇴",
    "counts": true
  },
  {
    "a3": "RUS",
    "numericId": "643",
    "name": "Russia",
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "flag": "🇷🇺",
    "counts": true
  },
  {
    "a3": "RWA",
    "numericId": "646",
    "name": "Rwanda",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇷🇼",
    "counts": true
  },
  {
    "a3": "BLM",
    "numericId": "652",
    "name": "Saint Barthélemy",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇧🇱",
    "counts": false
  },
  {
    "a3": "SHN",
    "numericId": "654",
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇸🇭",
    "counts": false
  },
  {
    "a3": "KNA",
    "numericId": "659",
    "name": "Saint Kitts and Nevis",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇰🇳",
    "counts": true
  },
  {
    "a3": "LCA",
    "numericId": "662",
    "name": "Saint Lucia",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇱🇨",
    "counts": true
  },
  {
    "a3": "MAF",
    "numericId": "663",
    "name": "Saint Martin",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇲🇫",
    "counts": false
  },
  {
    "a3": "SPM",
    "numericId": "666",
    "name": "Saint Pierre and Miquelon",
    "continent": "North America",
    "subregion": "North America",
    "flag": "🇵🇲",
    "counts": false
  },
  {
    "a3": "VCT",
    "numericId": "670",
    "name": "Saint Vincent and the Grenadines",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇻🇨",
    "counts": true
  },
  {
    "a3": "WSM",
    "numericId": "882",
    "name": "Samoa",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇼🇸",
    "counts": true
  },
  {
    "a3": "SMR",
    "numericId": "674",
    "name": "San Marino",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇸🇲",
    "counts": true
  },
  {
    "a3": "STP",
    "numericId": "678",
    "name": "São Tomé and Príncipe",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇸🇹",
    "counts": true
  },
  {
    "a3": "SAU",
    "numericId": "682",
    "name": "Saudi Arabia",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇸🇦",
    "counts": true
  },
  {
    "a3": "SEN",
    "numericId": "686",
    "name": "Senegal",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇸🇳",
    "counts": true
  },
  {
    "a3": "SRB",
    "numericId": "688",
    "name": "Serbia",
    "continent": "Europe",
    "subregion": "Southeast Europe",
    "flag": "🇷🇸",
    "counts": true
  },
  {
    "a3": "SYC",
    "numericId": "690",
    "name": "Seychelles",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇸🇨",
    "counts": true
  },
  {
    "a3": "SLE",
    "numericId": "694",
    "name": "Sierra Leone",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇸🇱",
    "counts": true
  },
  {
    "a3": "SGP",
    "numericId": "702",
    "name": "Singapore",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇸🇬",
    "counts": true
  },
  {
    "a3": "SXM",
    "numericId": "534",
    "name": "Sint Maarten",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇸🇽",
    "counts": false
  },
  {
    "a3": "SVK",
    "numericId": "703",
    "name": "Slovakia",
    "continent": "Europe",
    "subregion": "Central Europe",
    "flag": "🇸🇰",
    "counts": true
  },
  {
    "a3": "SVN",
    "numericId": "705",
    "name": "Slovenia",
    "continent": "Europe",
    "subregion": "Central Europe",
    "flag": "🇸🇮",
    "counts": true
  },
  {
    "a3": "SLB",
    "numericId": "90",
    "name": "Solomon Islands",
    "continent": "Oceania",
    "subregion": "Melanesia",
    "flag": "🇸🇧",
    "counts": true
  },
  {
    "a3": "SOM",
    "numericId": "706",
    "name": "Somalia",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇸🇴",
    "counts": true
  },
  {
    "a3": "ZAF",
    "numericId": "710",
    "name": "South Africa",
    "continent": "Africa",
    "subregion": "Southern Africa",
    "flag": "🇿🇦",
    "counts": true
  },
  {
    "a3": "SGS",
    "numericId": "239",
    "name": "South Georgia",
    "continent": "Antarctica",
    "subregion": "Other",
    "flag": "🇬🇸",
    "counts": false
  },
  {
    "a3": "KOR",
    "numericId": "410",
    "name": "South Korea",
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "flag": "🇰🇷",
    "counts": true
  },
  {
    "a3": "SSD",
    "numericId": "728",
    "name": "South Sudan",
    "continent": "Africa",
    "subregion": "Middle Africa",
    "flag": "🇸🇸",
    "counts": true
  },
  {
    "a3": "ESP",
    "numericId": "724",
    "name": "Spain",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇪🇸",
    "counts": true
  },
  {
    "a3": "LKA",
    "numericId": "144",
    "name": "Sri Lanka",
    "continent": "Asia",
    "subregion": "Southern Asia",
    "flag": "🇱🇰",
    "counts": true
  },
  {
    "a3": "SDN",
    "numericId": "729",
    "name": "Sudan",
    "continent": "Africa",
    "subregion": "Northern Africa",
    "flag": "🇸🇩",
    "counts": true
  },
  {
    "a3": "SUR",
    "numericId": "740",
    "name": "Suriname",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇸🇷",
    "counts": true
  },
  {
    "a3": "SJM",
    "numericId": "744",
    "name": "Svalbard and Jan Mayen",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇸🇯",
    "counts": false
  },
  {
    "a3": "SWE",
    "numericId": "752",
    "name": "Sweden",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇸🇪",
    "counts": true
  },
  {
    "a3": "CHE",
    "numericId": "756",
    "name": "Switzerland",
    "continent": "Europe",
    "subregion": "Western Europe",
    "flag": "🇨🇭",
    "counts": true
  },
  {
    "a3": "SYR",
    "numericId": "760",
    "name": "Syria",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇸🇾",
    "counts": true
  },
  {
    "a3": "TWN",
    "numericId": "158",
    "name": "Taiwan",
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "flag": "🇹🇼",
    "counts": false
  },
  {
    "a3": "TJK",
    "numericId": "762",
    "name": "Tajikistan",
    "continent": "Asia",
    "subregion": "Central Asia",
    "flag": "🇹🇯",
    "counts": true
  },
  {
    "a3": "TZA",
    "numericId": "834",
    "name": "Tanzania",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇹🇿",
    "counts": true
  },
  {
    "a3": "THA",
    "numericId": "764",
    "name": "Thailand",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇹🇭",
    "counts": true
  },
  {
    "a3": "TLS",
    "numericId": "626",
    "name": "Timor-Leste",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇹🇱",
    "counts": true
  },
  {
    "a3": "TGO",
    "numericId": "768",
    "name": "Togo",
    "continent": "Africa",
    "subregion": "Western Africa",
    "flag": "🇹🇬",
    "counts": true
  },
  {
    "a3": "TKL",
    "numericId": "772",
    "name": "Tokelau",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇹🇰",
    "counts": false
  },
  {
    "a3": "TON",
    "numericId": "776",
    "name": "Tonga",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇹🇴",
    "counts": true
  },
  {
    "a3": "TTO",
    "numericId": "780",
    "name": "Trinidad and Tobago",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇹🇹",
    "counts": true
  },
  {
    "a3": "TUN",
    "numericId": "788",
    "name": "Tunisia",
    "continent": "Africa",
    "subregion": "Northern Africa",
    "flag": "🇹🇳",
    "counts": true
  },
  {
    "a3": "TUR",
    "numericId": "792",
    "name": "Türkiye",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇹🇷",
    "counts": true
  },
  {
    "a3": "TKM",
    "numericId": "795",
    "name": "Turkmenistan",
    "continent": "Asia",
    "subregion": "Central Asia",
    "flag": "🇹🇲",
    "counts": true
  },
  {
    "a3": "TCA",
    "numericId": "796",
    "name": "Turks and Caicos Islands",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇹🇨",
    "counts": false
  },
  {
    "a3": "TUV",
    "numericId": "798",
    "name": "Tuvalu",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇹🇻",
    "counts": true
  },
  {
    "a3": "UGA",
    "numericId": "800",
    "name": "Uganda",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇺🇬",
    "counts": true
  },
  {
    "a3": "UKR",
    "numericId": "804",
    "name": "Ukraine",
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "flag": "🇺🇦",
    "counts": true
  },
  {
    "a3": "ARE",
    "numericId": "784",
    "name": "United Arab Emirates",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇦🇪",
    "counts": true
  },
  {
    "a3": "GBR",
    "numericId": "826",
    "name": "United Kingdom",
    "continent": "Europe",
    "subregion": "Northern Europe",
    "flag": "🇬🇧",
    "counts": true
  },
  {
    "a3": "USA",
    "numericId": "840",
    "name": "United States",
    "continent": "North America",
    "subregion": "North America",
    "flag": "🇺🇸",
    "counts": true
  },
  {
    "a3": "UMI",
    "numericId": "581",
    "name": "United States Minor Outlying Islands",
    "continent": "North America",
    "subregion": "North America",
    "flag": "🇺🇲",
    "counts": false
  },
  {
    "a3": "VIR",
    "numericId": "850",
    "name": "United States Virgin Islands",
    "continent": "North America",
    "subregion": "Caribbean",
    "flag": "🇻🇮",
    "counts": false
  },
  {
    "a3": "URY",
    "numericId": "858",
    "name": "Uruguay",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇺🇾",
    "counts": true
  },
  {
    "a3": "UZB",
    "numericId": "860",
    "name": "Uzbekistan",
    "continent": "Asia",
    "subregion": "Central Asia",
    "flag": "🇺🇿",
    "counts": true
  },
  {
    "a3": "VUT",
    "numericId": "548",
    "name": "Vanuatu",
    "continent": "Oceania",
    "subregion": "Melanesia",
    "flag": "🇻🇺",
    "counts": true
  },
  {
    "a3": "VAT",
    "numericId": "336",
    "name": "Vatican City",
    "continent": "Europe",
    "subregion": "Southern Europe",
    "flag": "🇻🇦",
    "counts": true
  },
  {
    "a3": "VEN",
    "numericId": "862",
    "name": "Venezuela",
    "continent": "South America",
    "subregion": "South America",
    "flag": "🇻🇪",
    "counts": true
  },
  {
    "a3": "VNM",
    "numericId": "704",
    "name": "Vietnam",
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "flag": "🇻🇳",
    "counts": true
  },
  {
    "a3": "WLF",
    "numericId": "876",
    "name": "Wallis and Futuna",
    "continent": "Oceania",
    "subregion": "Polynesia",
    "flag": "🇼🇫",
    "counts": false
  },
  {
    "a3": "ESH",
    "numericId": "732",
    "name": "Western Sahara",
    "continent": "Africa",
    "subregion": "Northern Africa",
    "flag": "🇪🇭",
    "counts": false
  },
  {
    "a3": "YEM",
    "numericId": "887",
    "name": "Yemen",
    "continent": "Asia",
    "subregion": "Western Asia",
    "flag": "🇾🇪",
    "counts": true
  },
  {
    "a3": "ZMB",
    "numericId": "894",
    "name": "Zambia",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇿🇲",
    "counts": true
  },
  {
    "a3": "ZWE",
    "numericId": "716",
    "name": "Zimbabwe",
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "flag": "🇿🇼",
    "counts": true
  }
]
